# permissions for end users to edit datasources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: datasource-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: arcadia
    app.kubernetes.io/part-of: arcadia
    app.kubernetes.io/managed-by: kustomize
  name: datasource-editor-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources/status
  verbs:
  - get
